version: '3'
services:
  backend:
    build: .
    ports:
      - "8112:8080"
    container_name: spring-cicd-demo-green
    environment:
      - TZ=Asia/Seoul
    networks:
      - servernetwork

networks:
  servernetwork:
    external: true
    driver: bridge
